// src/components/ui/button.tsx
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';
import type * as React from 'react';

import { cn } from '@/lib/utils';

const buttonVariants = cva(
	"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all cursor-pointer disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
	{
		variants: {
			variant: {
				default: 'bg-primary text-primary-foreground hover:bg-primary/90',
				destructive:
					'bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60',
				outline:
					'border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50',
				secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
				ghost: 'hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50',
				link: 'text-primary underline-offset-4 hover:underline',
			},
			size: {
				default: 'h-9 px-4 py-2 has-[>svg]:px-3',
				sm: 'h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5',
				lg: 'h-10 rounded-md px-6 has-[>svg]:px-4',
				icon: 'size-9',
				'icon-sm': 'size-8',
				'icon-lg': 'size-10',
			},
		},
		defaultVariants: {
			variant: 'default',
			size: 'default',
		},
	},
);

// =============================================================================
// BUTTON PROPS
// =============================================================================

interface ButtonProps extends React.ComponentProps<'button'>, VariantProps<typeof buttonVariants> {
	/** Render as child slot */
	asChild?: boolean;
	/** Icon to display on the left side of the button text */
	iconLeft?: React.ReactNode;
	/** Icon to display on the right side of the button text */
	iconRight?: React.ReactNode;
	/** Loading state - shows spinner and disables button */
	loading?: boolean;
	/** Full width button */
	fullWidth?: boolean;
}

function Button({
	className,
	variant = 'default',
	size = 'default',
	asChild = false,
	iconLeft,
	iconRight,
	loading = false,
	fullWidth = false,
	children,
	disabled,
	...props
}: ButtonProps) {
	// If asChild is true, we can't add icons - pass through as-is
	if (asChild) {
		return (
			<Slot
				data-slot="button"
				data-variant={variant}
				data-size={size}
				className={cn(buttonVariants({ variant, size }), fullWidth && 'w-full', className)}
				{...props}
			/>
		);
	}

	return (
		<button
			data-slot="button"
			data-variant={variant}
			data-size={size}
			disabled={disabled || loading}
			className={cn(buttonVariants({ variant, size }), fullWidth && 'w-full', className)}
			{...props}
		>
			{loading ? (
				<svg
					className="animate-spin size-4"
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
				>
					<circle
						className="opacity-25"
						cx="12"
						cy="12"
						r="10"
						stroke="currentColor"
						strokeWidth="4"
					/>
					<path
						className="opacity-75"
						fill="currentColor"
						d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
					/>
				</svg>
			) : (
				iconLeft
			)}
			{children}
			{!loading && iconRight}
		</button>
	);
}

export { Button, buttonVariants };
export type { ButtonProps };

// src/lib/components/forms/Button.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from 'svelte/elements';
	import type { Snippet } from 'svelte';

	interface Props extends HTMLButtonAttributes {
		/** Button variant */
		variant?: 'primary' | 'secondary' | 'danger' | 'ghost';
		/** Is the button in loading state */
		loading?: boolean;
		/** Loading text (shown with spinner during loading) */
		loadingText?: string;
		/** Button type */
		type?: 'button' | 'submit' | 'reset';
		/** Is the button disabled */
		disabled?: boolean;
		/** Button content */
		children?: Snippet;
		/** Icon slot (shown before text) */
		icon?: Snippet;
		/** Reference to the button element */
		buttonRef?: HTMLButtonElement | null;
	}

	let {
		variant = 'primary',
		loading = false,
		loadingText,
		type = 'button',
		disabled = false,
		children,
		icon,
		buttonRef = $bindable(null),
		...restProps
	}: Props = $props();

	const isDisabled = $derived(disabled || loading);
</script>

<button
	bind:this={buttonRef}
	{type}
	class="btn btn-{variant}"
	class:loading
	disabled={isDisabled}
	aria-busy={loading}
	{...restProps}
>
	{#if loading}
		<svg class="spinner" viewBox="0 0 24 24" aria-hidden="true">
			<circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round">
				<animate attributeName="stroke-dasharray" values="0 63;32 63;63 63;63 63" dur="1s" repeatCount="indefinite"/>
				<animateTransform attributeName="transform" type="rotate" from="0 12 12" to="360 12 12" dur="1s" repeatCount="indefinite"/>
			</circle>
		</svg>
		<span class="btn-text">{loadingText || ''}{@render children?.()}</span>
	{:else}
		{#if icon}
			<span class="btn-icon" aria-hidden="true">
				{@render icon()}
			</span>
		{/if}
		{#if children}
			<span class="btn-text">{@render children()}</span>
		{/if}
	{/if}
</button>

<style>
	.btn {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		gap: var(--spacing-2);
		padding: var(--spacing-3) var(--spacing-5);
		font-weight: var(--font-weight-semibold);
		font-size: var(--font-size-sm);
		border-radius: var(--radius-xl);
		border: none;
		cursor: pointer;
		transition:
			background-color var(--transition-fast),
			border-color var(--transition-fast),
			box-shadow var(--transition-fast),
			transform var(--transition-fast),
			opacity var(--transition-fast);
		min-height: var(--touch-target-min, 44px);
		min-width: var(--touch-target-min, 44px);
		touch-action: manipulation;
		-webkit-tap-highlight-color: transparent;
		-webkit-user-select: none;
		user-select: none;
		white-space: nowrap;
	}

	.btn:focus-visible {
		outline: 2px solid var(--color-primary-500);
		outline-offset: 2px;
	}

	.btn:active:not(:disabled) {
		transform: scale(0.97);
	}

	@media (prefers-reduced-motion: reduce) {
		.btn:active:not(:disabled) {
			transform: none;
		}
	}

	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	/* Variants */
	.btn-primary {
		background: var(--gradient-accent);
		color: white;
		box-shadow: var(--glow-coral);
	}

	.btn-primary:hover:not(:disabled) {
		box-shadow: var(--glow-coral-intense);
		transform: translateY(-1px);
	}

	.btn-secondary {
		background: var(--color-bg-subtle);
		color: var(--color-text-secondary);
		border: 1px solid var(--color-border);
	}

	.btn-secondary:hover:not(:disabled) {
		background: var(--color-bg-muted);
		color: var(--color-text-primary);
		border-color: var(--color-border-hover);
	}

	.btn-danger {
		background: linear-gradient(135deg, #F87171 0%, #EF4444 100%);
		color: white;
	}

	.btn-danger:hover:not(:disabled) {
		box-shadow: 0 0 20px rgba(239, 68, 68, 0.3);
		transform: translateY(-1px);
	}

	.btn-ghost {
		background: transparent;
		color: var(--color-text-tertiary);
		padding: var(--spacing-2) var(--spacing-4);
	}

	.btn-ghost:hover:not(:disabled) {
		color: var(--color-text-primary);
		background: var(--color-bg-subtle);
	}

	/* Loading state */
	.loading {
		pointer-events: none;
	}

	.spinner {
		width: 18px;
		height: 18px;
		flex-shrink: 0;
	}

	@media (prefers-reduced-motion: reduce) {
		.spinner {
			animation: none;
		}
		.spinner circle {
			stroke-dasharray: 32 63;
		}
	}

	.btn-icon {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 18px;
		height: 18px;
		flex-shrink: 0;
	}

	.btn-icon :global(svg) {
		width: 100%;
		height: 100%;
	}

</style>
